# -*- coding: utf-8 -*-
"""gender

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0AQaLcu1PDfZdaAsOkZCNPf4Pi4C4wQ
"""

# Path setting
import os
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/KISS_COUNT')
os.listdir()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 讀取資料
file_path = 'DATA_Kiss_count_gender_and_IQ.xlsx'
df = pd.read_excel(file_path)
df.columns = df.columns.str.strip()

# 篩選並處理資料
data = df[['Gender', 'IQ', 'Kiss Count', 'Age of First Kiss']].copy()
data['Gender'] = data['Gender'].str.strip().str.lower()  # 確保一致性
data = data[data['Gender'].isin(['male', 'female'])]     # 避免非預期值

# 設定繪圖樣式
sns.set(style="whitegrid")
palette = {'male': '#1f77b4', 'female': '#ff69b4'}  # 藍色與粉色

# 建立三張 boxplot
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Gender vs IQ
sns.boxplot(x='Gender', y='IQ', data=data, palette=palette, ax=axes[0])
axes[0].set_title('IQ by Gender')

# Gender vs Kiss Count
sns.boxplot(x='Gender', y='Kiss Count', data=data, palette=palette, ax=axes[1])
axes[1].set_title('Kiss Count by Gender')

# Gender vs Age of First Kiss
sns.boxplot(x='Gender', y='Age of First Kiss', data=data, palette=palette, ax=axes[2])
axes[2].set_title('Age of First Kiss by Gender')

# 顯示圖表
plt.tight_layout()
plt.show()